### ISSUE TITLE
No data retrived

### ISSUE THREAD

**Issue by ouranos6** [gieljnssns/kostalpiko-sensor-homeassistant#1]
Hello,

I manage to install and see the sensor in the interface but I have no information retrieved.

This is my configuration.yaml sensor section
```yaml
sensor:
- platform: kostal 
  host: 'http://192.168.1.36'
  username: pvwr
  password: pvserver
  monitored_conditions:
    - solar_generator_power
    - consumption_phase_1
    - consumption_phase_2
    - consumption_phase_3
    - current_power
    - total_energy
    - daily_energy
```

and as you can see below no datas... and believe me right now we have a lot of sun!
![image](https://user-images.githubusercontent.com/20718760/63004262-3e2dfe80-be7a-11e9-92b6-1d398e828aa2.png)

I'm using hassio version and I can't use PIP or at least I don't know how to do that...

I hope you can help me with that :) I'm super excited to integrate my little PV production to my Home Assistant interface.
