### ISSUE TITLE
kostal_piko_daily_energy vs utility_meter 

### ISSUE THREAD

**Issue by zibous** [gieljnssns/kostalpiko-sensor-homeassistant#13]
**Describe the bug**
I don't understand why the values of **utility_meter** (daily) do not match the **kostal_piko_daily_energy**?
The values of the utility_meter sensor are much higher than those of the kostal_piko_daily_energy?

|sensor    |  kWh |
|----------|------|
|sensor.ertrag_photovolatik_tag|	**24.35**	
|sensor.kostal_piko_daily_energy|   **15.65**

**Config yaml**
```
sensor:
  - platform: kostal
    host: !secret kostal_host  # "http://192.168.xx.xx"
    username: !secret kostal_username
    password: !secret kostal_password
    monitored_conditions:
      - current_power
      - total_energy
      - daily_energy
      - string1_voltage
      - string1_current
      - string2_voltage
      - string2_current
      - l1_voltage
      - l1_power
      - l2_voltage
      - l2_power
      - l3_voltage
      - l3_power
      - status

utility_meter:
  ertrag_photovolatik_day:
    source: sensor.kostal_piko_current_power
    cycle: daily
  ertrag_photovolatik_month:
    source: sensor.kostal_piko_current_power
    cycle: monthly
ertrag_photovolatik_year:
    source: sensor.kostal_piko_current_power
    cycle: yearly

```

**Additional context**
	

I am doing something wrong in the configuration.
