### ISSUE TITLE
Better support for multiple Piko's and adding the status as a sensor

### ISSUE THREAD

**Issue by Vedeneb** [gieljnssns/kostalpiko-sensor-homeassistant#7]
Hi,

first of all, thanks for this integration, it works flawlessly!
I have two suggestions/feature requests:

First, I have three identical Kostal Pikos (because we have a huge roof with lots of Solar Panels :)). I added them all the same way to the config:

```
- platform: kostal
  host: http://192.168.178.251
  username: pvserver
  password: aaa
  monitored_conditions:
    - current_power
    - ....
- platform: kostal
  host: http://192.168.178.252
  username: pvserver
  password: aaa
  monitored_conditions:
    - current_power
    - ....
- platform: kostal
  host: http://192.168.178.253
  username: pvserver
  password: aaa
  monitored_conditions:
    - current_power
    - ....
```

It does work, all entities have been registered successfully. However, they are called like this:
`sensor.kostal_piko_current_power`
`sensor.kostal_piko_current_power_2`
`sensor.kostal_piko_current_power_3`

which is ok, however I think a little configuration option for a custom name would be the better solution. So if I would set up the integration like this:
```
- platform: kostal
  name: Solar 1
  host: http://192.168.178.251
  username: pvserver
  password: aaa
  monitored_conditions:
    - current_power
    - ....
```
the entities would be called 
`sensor.solar_1_current_power`
and so on.

The second that would be great if you could add it would be a sensor exposing the current status of the Piko.
![image](https://user-images.githubusercontent.com/39202639/78509414-04ee2a00-778e-11ea-9e59-076eebd5adf4.png)

That way one could easily build automations to send notifications e.g. if the state changes to an error.

Thanks in advance and thanks again for the integration!

Vedeneb
